// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CatalogEntryView = { name: string, authors: string, homepage: string, license: string, version: string, shortDescription: string, description: string | null, iconUrl: string | null, };
