// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogEntryView } from "./CatalogEntryView";
import type { CatalogSourceView } from "./CatalogSourceView";

export type CatalogView = { entries: Array<CatalogEntryView>, source: CatalogSourceView, 
/**
 * Unix seconds of the fetch that produced `entries` (the cache's time when offline).
 */
fetchedAt: number, };
