// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitView } from "./CommitView";
import type { IssueView } from "./IssueView";

export type CmdError = { "kind": "noInstall", message: string, } | { "kind": "gameRunning", message: string, } | { "kind": "blocked", message: string, issues: Array<IssueView>, } | { "kind": "planExpired", message: string, } | { "kind": "cancelled", message: string, } | { "kind": "notFound", message: string, } | { "kind": "invalid", message: string, } | { "kind": "installFailed", message: string, folder: string, partial: CommitView, } | { "kind": "network", message: string, } | { "kind": "io", message: string, };
