// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommitView = { 
/**
 * Identities of the plugins installed (or replaced, for an update).
 */
installed: Array<string>, enabled: Array<string>, disabled: Array<string>, backup: string | null, 
/**
 * Couldn't tell whether the game is running; warn that it may overwrite `plugins.txt`.
 */
gameDetectionFailed: boolean, 
/**
 * Old copies a replace couldn't delete; the install itself succeeded.
 */
leftovers: Array<string>, };
