// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Emitted as the `download-progress` event while a plan downloads.
 */
export type DownloadProgress = { planId: number, catalogName: string, received: number, total: number | null, };
