// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateView } from "./UpdateView";

export type InstalledPluginView = { folder: string, identity: string, enabled: boolean, 
/**
 * Has an install record (installed or adopted by the manager).
 */
managed: boolean, catalogName: string | null, 
/**
 * The record's version; empty for an adopted plugin.
 */
installedVersion: string | null, 
/**
 * `plugin.txt`'s own `version`, purely informational.
 */
pluginVersion: string | null, update: UpdateView, about: string, authors: Array<string>, requires: Array<string>, optional: Array<string>, conflicts: Array<string>, gameVersion: string | null, };
