// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallKindView } from "./InstallKindView";

export type InstallView = { 
/**
 * Stable key for selecting this install (see `settings::install_key`).
 */
key: string, kind: InstallKindView, configDir: string, executable: string | null, 
/**
 * How the launch button would start it; `None` means there's no known way.
 */
launch: string | null, 
/**
 * Added by the user rather than auto-detected (decision H's "let the user override").
 */
userAdded: boolean, 
/**
 * `endless-sky --version`, when it could be read.
 */
gameVersion: string | null, };
