// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallView } from "./InstallView";

export type InstallsView = { installs: Array<InstallView>, 
/**
 * The install every other command acts on; `None` when nothing was found or added.
 */
selected: string | null, };
