// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameProcessView } from "./GameProcessView";
import type { InstallView } from "./InstallView";
import type { InstalledPluginView } from "./InstalledPluginView";
import type { ProfilesView } from "./ProfilesView";
import type { UnmanagedView } from "./UnmanagedView";

/**
 * One call's worth of everything the main views render, read fresh from disk.
 */
export type ManagerState = { install: InstallView | null, game: GameProcessView, plugins: Array<InstalledPluginView>, unmanaged: Array<UnmanagedView>, profiles: ProfilesView, 
/**
 * Folders adopted automatically during this call (decision B), for a notice.
 */
adopted: Array<string>, 
/**
 * The catalog wasn't loaded yet, so update status and adoption were skipped.
 */
catalogLoaded: boolean, };
