// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NoteView = { "kind": "optionalAvailable", plugin: string, optional: string, installed: boolean, };
