// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IssueView } from "./IssueView";
import type { MissingView } from "./MissingView";
import type { NoteView } from "./NoteView";
import type { PlanKind } from "./PlanKind";
import type { RequirementFixView } from "./RequirementFixView";
import type { StepView } from "./StepView";

/**
 * A pending plan, held by the backend until it's committed, discarded or superseded.
 */
export type PlanView = { planId: number, kind: PlanKind, 
/**
 * What the user asked for: a catalog name, identity, folder or profile name.
 */
target: string, steps: Array<StepView>, 
/**
 * Blocking: every one must be resolved or explicitly overridden (decision C).
 */
issues: Array<IssueView>, 
/**
 * Never blocking.
 */
notes: Array<NoteView>, fixes: Array<RequirementFixView>, 
/**
 * Identities `resolve_conflict` can disable to clear a `conflict` issue (install plans).
 */
resolvableConflicts: Array<string>, 
/**
 * Profile plans: entries the profile enables that aren't installed.
 */
missing: Array<MissingView>, 
/**
 * The installed game's version the checks ran against.
 */
gameVersion: string | null, 
/**
 * Uninstall plans for a plugin the manager didn't install (decision B).
 */
unmanagedTarget: boolean, };
