// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DriftView } from "./DriftView";
import type { MissingView } from "./MissingView";
import type { ProfileSummary } from "./ProfileSummary";

export type ProfilesView = { active: string | null, profiles: Array<ProfileSummary>, 
/**
 * Live `plugins.txt` vs the active profile (e.g. toggled in-game).
 */
drift: DriftView, 
/**
 * Plugins the active profile enables that aren't installed.
 */
missing: Array<MissingView>, };
