// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A way out of a `MissingRequirement`/`AmbiguousRequirement`.
 */
export type RequirementFixView = { requires: string, 
/**
 * It's installed but disabled: enable it (identity). Excludes the other two.
 */
enable: string | null, 
/**
 * One catalog entry to install. Excludes `candidates`.
 */
install: string | null, 
/**
 * Several catalog entries match; the user picks.
 */
candidates: Array<string>, };
