// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StepView = { "kind": "install", catalogName: string, identity: string, folder: string, version: string, 
/**
 * Pulled in by a `requires`, rather than the plugin the user asked for.
 */
dependency: boolean, } | { "kind": "update", catalogName: string, identity: string, folder: string, from: string, to: string, } | { "kind": "enable", identity: string, } | { "kind": "disable", identity: string, } | { "kind": "uninstall", folder: string, identity: string, };
