// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An unmanaged plugin with no single catalog match (decision B: "ask the user").
 */
export type UnmanagedView = { folder: string, identity: string, 
/**
 * Empty: not in the catalog at all. Several: ambiguous, the user picks one.
 */
candidates: Array<string>, };
