// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateView = { "kind": "upToDate" } | { "kind": "available", from: string, to: string, } | { "kind": "unknown" } | { "kind": "notInCatalog" } | { "kind": "unmanaged" } | { "kind": "unchecked" };
